services:
  docassemble:
    image: jhpyle/docassemble:latest
    hostname: docassemble
    stopgrace_period: 1m30s
    environment:
      CONTAINERROLE=all
      DBPREFIX=postgresql
      DBNAME=docassemble
      DBUSER=docassemble
      DBPASSWORD=abc123
      DBHOST=localhost
      USEHTTPS=false
      DAHOSTNAME=app.editioneo.com
      USELETSENCRYPT=false
      S3ENABLE=false
    stop_grace_period: 1m
