services:
  docassemble:
    image: jhpyle/docassemble:latest
    hostname: docassemble
    ports:
      - "8080:8080"
      - "4430:4430"
    environment:
      CONTAINERROLE=all
      DBPREFIX=postgresql
      DBNAME=docassemble
      DBUSER=docassemble
      DBPASSWORD=abc123
      DBHOST=localhost
      USEHTTPS=false
      DAHOSTNAME=app.editioneo.com
      USELETSENCRYPT=false
      S3ENABLE=false
