services:
	docassemble:
		image: jhpyle/docassemble:latest
    hostname: docassemble
    containername: docassemble
    stopgrace_period: 1m30s
    environment:
      – CONTAINERROLE=all
      – DBPREFIX=postgresql+psycopg2://
      – DBNAME=docassemble
      – DBUSER=docassemble
      – DBPASSWORD=abc123
      – DBHOST=localhost
      – USEHTTPS=false
      – DAHOSTNAME=app.editioneo.com
      – USELETSENCRYPT=false
      – S3ENABLE=false
